---
title: "Installation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The prerequisites for LeafCutter are

* [samtools](http://samtools.sourceforge.net/) should be available on your PATH
* Python 2.7 (earlier versions may be OK)
* R (version 3.3.3, earlier versions may be OK)

To download the code (you'll need this for the leafcutter scripts)
```
git clone https://github.com/davidaknowles/leafcutter
```

### Installing the R package

#### Using devtools (recommended)

To compile the R package to perform differential splicing analysis and make junction plots we recommend you install using devtools (this should install the required R package dependencies for you). Fire up R and run:
```
if (!require("devtools")) install.packages("devtools", repos='http://cran.us.r-project.org')
devtools::install_github("davidaknowles/leafcutter/leafcutter")
```

We've had a report (thanks to Peter Carbonetto) that it may be necessary to restart R before trying to load `leafcutter` because `dplyr` may get updated during the installation process.

#### From source

Alternatively you can install from source. You'll need to manually install the following R packages: `Rcpp, rstan, foreach, ggplot2, R.utils, gridExtra, reshape2, Hmisc, dplyr, doMC, optparse, shiny, intervals, shinycssloaders, DT, gtables`. Then make sure you're in the `leafcutter` package sub-directory (you should see subdirectories called `src, R, tests` etc) and run
```
R CMD INSTALL --build .
```
If you see errors try installing the `roxygen2` package and running
```
R CMD INSTALL --preclean --build .
```
which will attempt to use `stan` to rebuild the C++ code from the `.stan` files in `exec`. 

#### Using conda

If you are a 64-bit Linux `conda` user ( [installation instructions](https://conda.io/docs/install/quick.html#miniconda-quick-install-requirements) ) we have an experimental package which can be installed using
```
conda install -c davidaknowles r-leafcutter
```
We will build macOS and Windows packages if there is demand for this. 
